class Whoop(object):

    disqus       = '''<div id="disqus_thread"></div><script type="text/javascript">var disqus_shortname = 'blogfy_';(function() {var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);})();</script><noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript><a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>'''

    intensedebate = '''<script>var idcomments_acct='601ab824df9337dc74bf6b4b42821319';var idcomments_post_id;var idcomments_post_url;</script><span id="IDCommentsPostTitle" style="display:none"></span><script type='text/javascript' src='https://www.intensedebate.com/js/genericCommentWrapperV2.js' async></script>'''

    sitemap      = '<?xml version="1.0" encoding="{0}" ?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"><!-- Generated by Blogfy https://github.com/wifiextender/blogfy -->{1}</urlset>'

    sidebar      = '<aside id="sidebar"><ul><li class="block"><div class="sidebar-top"></div><div class="sidebar-content">{0}</div><div class="sidebar-bottom"></div></li></ul></aside>'

    git_script   = '<script src="{0}css/js/jquery.min.js" type="text/javascript"></script><script src="{0}css/js/github.js" type="text/javascript"></script><script type="text/javascript">$(function() {1}</script>'

    post_body    = '<h1>{0}</h1><div class="date-left"><span class="label label-default">{1} Author: {2}</span></div><div class="articleline2"></div><br /><br />'

    front_pagi   = '<ul class="pager"><li class="previous"><a href="{0}page/1/">Older Entries</a></li></ul>'

    older_newer  = '<ul class="pager"><li class="previous"><a href="{0}">Newer Entries</a></li><li class="next"><a href="{1}">Older Entries</a></li></ul>'

    sitemap_loc  = '<url><loc>{0}</loc><lastmod>{1}</lastmod><priority>0.5</priority></url>'

    tags_sidebar = '<div class="panel panel-primary"><div class="panel-heading"><h3 class="panel-title">Popular Tags</h3></div><div class="panel-body"><div id="popular_tagz"></div></div></div>'

    recent_bar   = '''
<div class="list-group"><div class="panel panel-primary"><div class="panel-heading"><h3 class="panel-title">Recent Posts</h3></div><div id="recent_poztz"></div></div></div>
'''

    contact      = '''
<p>To prevent the email crawlers and spam bots from getting my email address, and care about our privacy, you are allowed to contact me only with encrypted emails. Wrote a fairly small and easy to follow tutorial about email encryption.</p>

<p>Get my <a href="<!-- web_addr -->img/file/pubkey.asc" target="_blank">public key here</a> and import it in your keyring.</p>

<p>Fingerprint = <strong>2044 4EEE 8C29 30E9 9A87  9E1D 2274 B73C 896A E578</strong></p>

<p>Long key ID = 2274B73C896AE578, Short key ID = 896AE578</p>

<p>Useful links - <a href="https://github.com/wifiextender?tab=repositories" target="_blank">GitHub Repos</a>, <a href="<!-- web_addr -->atom.xml">Atom(rss)</a>, <a href="<!-- web_addr -->sitemap.xml">Sitemap</a>
'''

    font_link    = """<a class='fit-tag' style='font-size:{0}px' href='{1}tags/{2}/'>{2}</a>&nbsp;"""

    span         = '<span>{0}</span>&nbsp;<a href="{1}">{2}</a><br />'

    last_page    = '<li class="next"><a href="{0}">Older Entries</a></li>'

    atom         = '''<?xml version="1.0" encoding="{0}"?><feed xmlns="http://www.w3.org/2005/Atom"><title><![CDATA[{1}]]></title><link href="{2}atom.xml" rel="self"/><link href="{2}"/><updated>{3}</updated><id>{2}</id><author><name><![CDATA[{4}]]></name></author><generator uri="https://github.com/wifiextender/blogfy">Blogfy</generator>{5}</feed>'''

    atom_entries = '''<entry><title type="html"><![CDATA[{0}]]></title><link href="{1}"/><updated>{2}</updated><id>{1}</id><content type="html"><![CDATA[{3}<br /><a href="{1}">Read more</a>]]></content></entry>'''

    os_script    = '''var Detection={mobile:["Android","iPhone","iPod","iPad","Symbian"],shorter:["Linux","Free","Open","NetBSD","BSD","Mac","Win","Sun","HP","Play","Web","QNX","BeOS","X11","OS/2"],longer:["Linux","FreeBSD","OpenBSD","NetBSD","BSD","Macintosh","Windows","SunOS","Hewlett-Packard","PlayStation","WebTV OS","QNX","BeOS","UNIX","OS/2"],found:"unknown",findOS:function(arr,os,mobile_bool){var x;for(x=0;x<arr.length;x++)if(os.indexOf(arr[x])!=-1){this.found=(mobile_bool?arr[x]:this.longer[x]);break}},init:function(){var itsmobile=navigator.userAgent.match(/(Android)|(iPhone)|(iPod)|(iPad)|(Symbian)/i);if(itsmobile)this.findOS(this.mobile,navigator.userAgent,true);else this.findOS(this.shorter,navigator.platform,false)}};function showOS(){Detection.init();alert("Your OS is: "+Detection.found)}'''

    tags_recent  = '''document.getElementById("recent_poztz").innerHTML=("<ul class='list-unstyled'>{0}</ul>");document.getElementById("popular_tagz").innerHTML=("{1}");'''
