#!/usr/bin/env bash

# I know ... I know ... it's lame

ipt='/sbin/iptables'
NIC='wlan0'
proc_net='/proc/sys/net/ipv4'
SYSCTL='/usr/sbin/sysctl'

# clear current ruleset
"${ipt}" -F
"${ipt}" -X
"${ipt}" -Z

#iptables -A TCP -p tcp --dport 22 -j ACCEPT

# the default policy
"${ipt}" -P INPUT DROP
"${ipt}" -P FORWARD DROP
"${ipt}" -P OUTPUT ACCEPT

# allow traffic on the loopback interface
"${ipt}" -A INPUT -i lo -j ACCEPT

"${ipt}" -A INPUT -i ${NIC} -p tcp ! --syn -m state --state NEW  -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix "Drop Syn"

"${ipt}" -A INPUT -i ${NIC} -p tcp ! --syn -m state --state NEW -j DROP

"${ipt}" -A INPUT -i ${NIC} -f  -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix "Fragments Packets"

"${ipt}" -A INPUT -i ${NIC} -f -j DROP

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags ALL FIN,URG,PSH -j DROP

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags ALL ALL -j DROP

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags ALL NONE -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix "NULL Packets"

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags ALL NONE -j DROP

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags SYN,RST SYN,RST -j DROP

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags SYN,FIN SYN,FIN -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix "XMAS Packets"

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags FIN,ACK FIN -m limit --limit 5/m --limit-burst 7 -j LOG --log-level 4 --log-prefix "Fin Packets Scan"

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags FIN,ACK FIN -j DROP

"${ipt}" -A INPUT -i ${NIC} -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP

"${ipt}" -A INPUT -i ${NIC} -m state --state ESTABLISHED,RELATED -j ACCEPT

"${ipt}" -A OUTPUT -o ${NIC} -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

"${ipt}" -A INPUT -p icmp --icmp-type 8 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT

"${ipt}" -A OUTPUT -p icmp --icmp-type 0 -m state --state ESTABLISHED,RELATED -j ACCEPT

"${ipt}" -A INPUT -p tcp --dport 53 -j DROP

"${ipt}" -A INPUT -d 255.255.255.255/0.0.0.255 -j DROP
"${ipt}" -A INPUT -d 224.0.0.1 -j DROP

"${ipt}" -A INPUT -j LOG


echo 10 > "${proc_net}"/neigh/${NIC}/locktime
echo 50 > "${proc_net}"/neigh/${NIC}/gc_stale_time

# echo 1 > "${proc_net}"/icmp_echo_ignore_all
# echo 1 > "${proc_net}"/icmp_echo_ignore_broadcasts
# echo 1 > "${proc_net}"/ip_forward
# echo 10 > "${proc_net}"/ipfrag_time
# echo 5 > "${proc_net}"/icmp_ratelimit
# echo 1 > "${proc_net}"/tcp_syncookies
# echo 0 > "${proc_net}"/conf/${NIC}/accept_redirects
# echo 1 > "${proc_net}"/conf/${NIC}/log_martians
# echo 0 > "${proc_net}"/conf/${NIC}/proxy_arp
# echo 0 > "${proc_net}"/conf/${NIC}/send_redirects
# echo 1 > "${proc_net}"/conf/${NIC}/secure_redirects
# echo 1 > "${proc_net}"/conf/all/secure_redirects
# echo 1 > "${proc_net}"/icmp_ignore_bogus_error_responses
# echo 5 > "${proc_net}"/igmp_max_memberships
# echo 2 > "${proc_net}"/igmp_max_msf
# echo 1024 > "${proc_net}"/tcp_max_orphans
# echo 2 > "${proc_net}"/tcp_syn_retries
# echo 2 > "${proc_net}"/tcp_synack_retries
# echo 1 > "${proc_net}"/tcp_abort_on_overflow
# echo 30 > "${proc_net}"/tcp_fin_timeout
# echo 70 > "${proc_net}"/tcp_keepalive_intvl
# echo 0 > "${proc_net}"/route/redirect_number
# echo 1 > "${proc_net}"/conf/all/rp_filter
# echo 1 > "${proc_net}"/conf/${NIC}/rp_filter
# echo 0 > "${proc_net}"/conf/all/accept_source_route
# echo 61 > "${proc_net}"/ip_default_ttl
# echo 0 > "${proc_net}"/tcp_window_scaling
# echo 1 > "${proc_net}"/tcp_sack
# echo 1 > "${proc_net}"/tcp_ecn
# echo 0 > "${proc_net}"/conf/all/send_redirects
# echo 0 > "${proc_net}"/conf/default/send_redirects
# echo 2048 > "${proc_net}"/conf/default/tcp_max_syn_backlog
# echo 2048 > "${proc_net}"/conf/all/tcp_max_syn_backlog
# echo 3 > "${proc_net}"/conf/default/tcp_synack_retries
# echo 3 > "${proc_net}"/conf/all/tcp_synack_retries
# echo 3 > "${proc_net}"/conf/default/tcp_syn_retries
# echo 3 > "${proc_net}"/conf/all/tcp_syn_retries
# echo 1 > "${proc_net}"/conf/default/arp_filter
# echo 1 > "${proc_net}"/conf/all/arp_filter
# echo 1 > "${proc_net}"/conf/default/tcp_tw_recycle
# echo 1 > "${proc_net}"/conf/all/tcp_tw_recycle
# echo 0 > "${proc_net}"/conf/all/tcp_ignore_ack
# echo 0 > "${proc_net}"/conf/defaul/tcp_ignore_ack
# echo 0 > "${proc_net}"/conf/all/tcp_ignore_bogus
# echo 0 > "${proc_net}"/conf/default/tcp_ignore_bogus
# echo 0 > "${proc_net}"/conf/all/tcp_ignore_synfin
# echo 0 > "${proc_net}"/conf/default/tcp_ignore_synfin

pkill dhcpcd
$SYSCTL --load '/etc/sysctl.conf'
rc-service iptables save
rc-service iptables restart
