#!/usr/bin/env bash

# Copyright 04/18/2016 Aaron Caffrey https://github.com/wifiextender

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.

_retsum() {
    cat ../js/"${1}" | openssl dgst -sha256 -binary | openssl enc -base64
}

_make_new_sums() {
    hljsTheme=$(cat ./temp/highlight.js-master/src/styles/agate.css \
        ../css/myBadAss.css | ./cleancss --s0 | base64 --wrap=0)
    ./html-minifier --minify-js --remove-comments --collapse-whitespace \
        index-dev.html | sed -e "s|@hljs-theme@|${hljsTheme}|g" \
            > ../index.html

    # Chromium sha sum verification is
    # too buggy. Fails to verify the
    # resources sha sums when you
    # consistently refresh the page.
    #| \
    #        sed \
    #        -e "s|@enginesum@|`_retsum engine.min.js`|g" \
    #        -e "s|@configsum@|`_retsum config.js`|g" \
    #            > ../index.html
}

_wget_hairyball() {
    wget "${1}" -O "temp/${2}.tar.gz"
    tar -xf "temp/${2}.tar.gz" -C 'temp'
}

setup() {
    mkdir -p --mode=700 'temp'

    #_wget_hairyball 'https://github.com/mishoo/UglifyJS2/archive/master.tar.gz' 'uglify'
    #_wget_hairyball 'https://github.com/chjj/marked/archive/master.tar.gz' 'marked'
    _wget_hairyball 'https://github.com/isagalaev/highlight.js/archive/master.tar.gz' 'hljs'

    ln -sf ./node_modules/.bin/{uglifyjs,html-minifier,cleancss} .

    ./uglifyjs --compress --mangle -- \
        './node_modules/marked/lib/marked.js' > marked.min.js

    _build_hljs
}


_build_hljs() {
    declare -a _bash_keywords_to_add

    cd 'temp/highlight.js-master'
    npm install

    node 'tools/build.js' :common
    cp -r 'build/highlight.pack.js' ../../highlight.min.js
    cd ../..


    # Add more bash keywords to be higlighted
    _bash_keywords_to_add=(
        'zcompile chroot ps mirrorselect links'
        'reboot fsck nmap mkswap swapon apt'
        'adduser modprobe split whoami date'
        'eselect pacaur yaourt configure cat'
        'gpasswd groups su rpm startx coredumpctl'
        'ping systemctl genfstab pacstrap eix locale'
        'hwclock wget mysql ssh ufw iptables ifconfig'
        'ip passwd tar pacman abs cp makepkg visudo'
        'gpg dirmngr mkdir shred dd emerge fdisk ln ls'
        'lsblk mount umount mkfs cryptsetup sysctl openssl'
        'export gpg2 useradd grub2 arch grub nano vi vim'
        'apt-get yum chkconfig mkinitcpio python gcc sed'
        'gawk awk sh touch git chmod chown make sudo patch'
        'cfdisk svn mv service rm equery qlist qlop'
)
    _dat_quoting="${_bash_keywords_to_add[@]}"
    sed -i "s|zcompile|${_dat_quoting}|g" 'highlight.min.js'
}

_glue_gemini() {

    cat src/view/new_edit_settings/*.js src/view/*.js \
        src/sidebar/*.js 'src/detectOS.js' \
        'src/listeners_funcs.js' > '/tmp/mega.js'

    # insert mega.js at line 270
    sed -e '270r /tmp/mega.js' 'src/main.js' > '/tmp/main.js'

    num=`gawk 'END {print NR}' /tmp/main.js`
    let "num=num-6"

    # insert the Event Listeners to the very bottom
    sed -e "${num}r src/global_listeners.js" '/tmp/main.js' > /tmp/geminiblog-glued.js
}

build() {
    _glue_gemini

    ./uglifyjs --compress --mangle -- \
        marked.min.js /tmp/geminiblog-glued.js highlight.min.js > ../js/engine.min.js

    _make_new_sums
}

clean() {
    rm -rf ./uglifyjs ./html-minifier ./temp \
        ./marked.min.js ./node_modules ./cleancss
}


main() {
    declare -a _targets
    _targets=('setup' 'build' 'clean')
    [[ -z $1 ]] || [[ ! " ${_targets[@]} " =~ " $1 " ]] \
        || [[ "${EUID}" == 0 ]] && {
        printf '%s\n' 'Error: stupid input detected.'
        return
    }

    case "${1}" in
        setup)     setup     ;;
        build)     build     ;;
        clean)     clean     ;;
    esac
}

main "$@"
