class Whoop(object):

    disqus      = '''<div id="disqus_thread"></div><script type="text/javascript">var disqus_shortname = 'blogfy_';(function() {var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);})();</script><noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript><a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>'''

    rss         = '<?xml version="1.0" encoding="UTF-8" ?><rss version="2.0"><channel><title>{0}</title><link>{1}</link><description>{2}</description>{3}</channel></rss>'

    sitemap     = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"><!-- Generated by Blogfy https://github.com/wifiextender/blogfy -->{0}</urlset>'

    sidebar     = '<aside id="sidebar"><ul><li class="block"><div class="sidebar-top"></div><div class="sidebar-content">{0}</div><div class="sidebar-bottom"></div></li></ul></aside>'

    git_base    = '<script src="{0}css/js/jquery.min.js" type="text/javascript"></script><script src="{0}css/js/github.js" type="text/javascript"></script><script type="text/javascript">$(function() {1}</script>'

    post_body   = '<h1>{0}</h1><div class="border-clazz date-left"><span class="label label-default">{1} Author: {2}</span></div><div class="articleline2"></div><br /><br />'

    rss_item    = '<item><title>{0}</title><pubDate>{1}</pubDate><link>{2}</link><description>{3}</description></item>'

    front_pagi  = '<ul class="pager"><li class="previous"><a href="{0}page/1/">Older Entries</a></li></ul>'

    older_newer = '<ul class="pager"><li class="previous"><a href="{0}">Newer Entries</a></li><li class="next"><a href="{1}">Older Entries</a></li></ul>'

    sitemap_loc = '<url><loc>{0}</loc><lastmod>{1}</lastmod><priority>0.5</priority></url>'

    tags_sidebar = '<div class="panel panel-primary"><div class="panel-heading"><h3 class="panel-title">Popular Tags</h3></div><div class="panel-body"><!-- tags_body --></div></div>'

    recent_bar  = '''
<div class="list-group"><div class="panel panel-primary"><div class="panel-heading"><h3 class="panel-title">Recent Posts</h3></div><ul class="list-unstyled"><!-- recent_posts --></ul></div></div>
'''

    contact     = '''
<p>To prevent the email crawlers and spam bots from getting my email address, and care about our privacy, you are allowed to contact me only with encrypted emails. Wrote a fairly small and easy to follow tutorial about email encryption.</p>

<p>Get my <a href="http://linux.sytes.net/img/file/pubkey.asc" target="_blank">public key here</a> and import it in your keyring. Hit me up with a simple email along with your public key. Once I've imported your public key will encrypt &amp; sign the email reply. Alternatively you can get my public key from the <strong>keys.gnupg.net</strong> key server with: <code>gpg --search-keys 'Aaron Caffrey'</code></p>

<p>Fingerprint = <strong>CF03 3489 E6A7 5CD9 B895  F251 148A 94F9 AA92 AE64</strong></p>

<p>Long key ID = 148A94F9AA92AE64, Short key ID = AA92AE64</p>

<p>Useful links - <a href="https://github.com/wifiextender?tab=repositories" target="_blank">GitHub Repos</a>, <a href="http://linux.sytes.net/rss.xml">RSS</a>, <a href="http://linux.sytes.net/sitemap.xml">Sitemap</a>
'''

    font_link  = '<a style="font-size:{0}px" href="{1}tags/{2}/">{2}</a>&nbsp;'

    span       = '<span>{0}</span>&nbsp;<a href="{1}">{2}</a><br />'

    last_page  = '<li class="next"><a href="{0}">Older Entries</a></li>'